### ISSUE TITLE
Documentation how to use routing engines

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/pyvroom#89]
We should document how to use a routing backend to prevent issues like #88. I’ll actually have to educate myself there a bit too, so I can take that.

**Comment by L0G1C06** [comment]
The code where i define the profile is the next:

problem_instance.add_vehicle([vroom.Vehicle(vehicle['id'], start=[start_lat, start_lng], end=[end_lat, end_lng], profile="car")])

I am not passing any custom matrix because I am using a JSON file that contains the addresses of all the points, with their respective longitudes and latitudes.
